### ISSUE TITLE
Could this idea work to use PinSim with Oculus Quest?

### ISSUE THREAD

**Issue by smokeandlights** [Jerware/PinSim#3]
I had an idea on how to make pinsim work with Oculus Quest, but I didn't know if it has been tried before:

Plugging directly into quest with a microUSB cable and a USB-A -> USB-C adapter seems to provide no power to the teensy.

Will the Quest recognize the PinSim if you use a powered USB-C hub, with a microUSB cable in a USB-A port, and the Quest attached to the "main" USB-C connector?

I apologize if this isn't the right place for this question. It seemed the most relevant spot to post it.

**Comment by Jerware** [comment]
Hm... I get power to the Teensy, but the controls don't work because the Quest apparently doesn't have XInput support (though Go does). Did you see [my post about getting it to work using a standards adapter and custom firmware](https://www.reddit.com/r/OculusQuest/comments/cpluc2/pinsim_on_quest_for_pinball_fx2_vr/)?

**Comment by smokeandlights** [comment]
Interesting. I'll have to check my adapters. I had not seen that post. Odd, since I follow you.Thanks, I'll try those steps!
