### ISSUE TITLE
Adding plunger interfering with accelerometer

### ISSUE THREAD

**Issue by g-coded** [Jerware/PinSim#5]
After trying to set up a plunger, the accelerometer refuses to work.  I only get feedback when the plunger is 'zeroed/centered' and this is still random and only shows extreme values.  I have tried a spare pinsim board and and a spare acc board and I am getting the same results.  I have also overwritten the hex with a 'blink' program(then the pinsim), and the plunger still looks for a signal(nothing connected).

**Comment by Jerware** [comment]
If the plunger is pulled, it disables the accelerometer so you don't get tilt warnings from plunging the ball. Why do you need the accelerometer to work while you're plunging?

**Comment by g-coded** [comment]
That makes sense.  Knowing this I can stop troubleshooting components.

  I am in the building phase so I was just testing adding a potentiometer.  The pot is giving me feedback when left in a neutral position and grounding the signal wire isn't helping.  I figured I could overwrite the hex file to restore defaualts(no plunger connected/zeroed), but I'm somehow still getting feedback from that axis.  Is there a way to disable the plunger input?

EDIT:  I homed the plunger again, it seems that trying to home it at the limits isn't stable enough(cheap pots).  Is there any dead zone for the plunger signal disabling the accelerometer?  I was going to try using a rotary pot, but I'm worried that any movement might create an unwanted signal.

**Comment by cjdw94** [comment]
Sorry to re-open this, but I'm currently going through archive.org and piecing together my own PinSim controller.  During my initial attempt at building, the accelerometer was working beautifully.  But after my last test, it wasn't working at all.  Could that have anything to do with the plunger lead?  I tried attaching it to ground, but that didn't seem to bring the accelerometer back to life.


Edit:  Resolved, see below.

**Comment by cjdw94** [comment]
I should probably mention that my building stage is still in its infancy.  Mostly it has just been attaching wires and making sure the correct inputs are registered.

Also - off topic, but the last time I tried my PinSim with the joystick attached, the joystick was registering multiple presses for each direction.  Left would go left twice, right would go right twice, etc. etc.  Any insight/thoughts there?

Edit:  Resolved, see below.

**Comment by cjdw94** [comment]
Edit:  Please disregard my previous posts - I finally have a working PinSim box (cardboard, but wood is coming) - I had to cheat and hardwire some of the buttons because the screw terminals weren't holding well enough, but everything works as it should.  The issue with the joystick resolved itself - attaching rumble motors was causing the controller to sporadically disconnect, but I read that with the LED(s) and motors, it might be pulling more power through the USB port than the average controller.  I tried a different cable, and added a powered USB hub and that seems to have solved that problem.  I learned the PinSim/Teensy LC combo is temperamental with some connections, but after reflowing some wires, everything is working as it should.  I even have a plunger successfully installed.  Thanks so much for coming up with this project!   Even if I might be the only one building one in 2024, lol.
